- name: mysql Configure
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: "ExpenseApp@1"
    login_host: "mysql.learnaws.space"
  tasks:
  - name: Install PyMySQL
    ansible.builtin.pip:
      name: PyMySQL
      state: present
    executable: pip3.9

  - name: Install MySQL server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: Ensure MySQL service is started and enabled
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to MySQL server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"  
    ignore_errors: true
    register: mysql_info

  - name: Display MySQL info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  